// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRZBQNWIxybGdis-XM3HWOYrZzFa0PxJw',
    appId: '1:963267905186:web:0b68db99d5088c93f2f9fb',
    messagingSenderId: '963267905186',
    projectId: 'test-67354',
    authDomain: 'test-67354.firebaseapp.com',
    storageBucket: 'test-67354.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuSIx8qd08ND3eVr8Bba0LiZHN6BjrFgw',
    appId: '1:963267905186:android:fac2c1af95d44397f2f9fb',
    messagingSenderId: '963267905186',
    projectId: 'test-67354',
    storageBucket: 'test-67354.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwS0fV4gfQWyvuQ46AJR05Qkz_46zph8',
    appId: '1:963267905186:ios:bb61d816c109a678f2f9fb',
    messagingSenderId: '963267905186',
    projectId: 'test-67354',
    storageBucket: 'test-67354.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEwS0fV4gfQWyvuQ46AJR05Qkz_46zph8',
    appId: '1:963267905186:ios:bb61d816c109a678f2f9fb',
    messagingSenderId: '963267905186',
    projectId: 'test-67354',
    storageBucket: 'test-67354.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
